Json parser c
lambdaclass/cairo-vm.c pull request #14
Opened 2023-07-13 18:23 UTC by toni-calvin

2023-07-17 20:23 UTC, Oppen commented on src/parser.cpp
> +  Program* allocate(const char *filename) {
C (and thus `extern "C"`) has no namespaces, so `allocate` as a symbol name is bound to produce name clashes. Consider something like `allocate_program` instead.

2023-07-17 20:23 UTC, Oppen commented on src/parser.cpp
> +    size_t size = st.st_size;
This is prone to [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) vulnerabilities. If you're already receiving the path, maybe consider opening the file and parsing already? You can get the size from the open file, which guarantees you at least have the same file rather than just the same path (you should probably lock it tho).

2023-07-17 20:23 UTC, Oppen commented on src/parser.cpp
> +    return (Program *)malloc(size * sizeof(int));
This seems quite odd. You're converting an allocation for `size` (where `size` is the number of __bytes__ of your file) `int`s and then casting it to a `struct Program`. Are we sure the sizes match or are at least compatible?

2023-07-17 20:23 UTC, Oppen commented on src/parser.cpp
> +  void parseArray(const simdjson::dom::array elemArray, char **structArray) {
Is it valid to pass a fully qualified path in an `extern "C"` block?

2023-07-17 20:23 UTC, Oppen commented on src/parser.cpp
> +    structArray = (char **)malloc(elements * max_chars * sizeof(char));
Since the array will contain pointers to strings, shouldn't this be:
```suggestion
    structArray = (char **)malloc(elements * sizeof(char*));
```

2023-07-17 20:23 UTC, Oppen commented on test/parser_test.c
> +  assert(program->data == expected_data);
This performs a pointer comparison, so it will never succeed. What you want here is a deep string comparison. I can't think of many options beyond `strcmp` inside a loop.

2023-07-19 16:10 UTC, toni-calvin commented on src/parser.cpp
> +    structArray = (char **)malloc(elements * max_chars * sizeof(char));
Yes, you are totally correct, i did not know how allocation worked so i simply put some extra memory. 
On last commit allocations have changes. 
Still not sure if done correctly.

2023-07-19 16:12 UTC, toni-calvin commented on test/parser_test.c
> +  assert(program->data == expected_data);
Yes, i used you advice to compare the strings. 
Now they are not strings anymore so the comparison is between uints64, can be done with ==

2023-07-19 16:13 UTC, toni-calvin commented on src/parser.cpp
> +    return (Program *)malloc(size * sizeof(int));
Nope, the size was not matching at all.

2023-07-19 16:17 UTC, toni-calvin commented on src/parser.cpp
> +  void parseArray(const simdjson::dom::array elemArray, char **structArray) {
I don't think i understand you, do you mean i shouldn't pass the fully library path as a function parameter?

2023-07-20 16:45 UTC, mmsc2 commented on lambdaworks/lib/lambdaworks.h
> +#endif
add new line please.

2023-07-20 16:45 UTC, mmsc2 commented on lambdaworks/lib/lambdaworks.h
> +#pragma once
i always suggest o use #ifndef delcarations in the header files to avoid possible circular dependencies

2023-07-20 16:45 UTC, mmsc2 commented on src/parser.h
> +#endif
new line

2023-07-20 17:07 UTC, Oppen commented on lambdaworks/lib/lambdaworks.h
> +#pragma once
Isn't `#pragma once` enough to deal with that?

2023-07-20 17:37 UTC, Oppen requested changes

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +	sscanf(hex, "%" SCNx64, &num);
If the string passed doesn't match we'll be handing out an uninitialized value. Consider initializing `num` to something (possibly `0`?).

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +		program = nullptr;
This doesn't have any significant effect. You're overwriting a copy of the pointer that will cease to exist once the function returns. And if it had, you'd probably be leaking memory anyway.

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +void parse_attributes(simdjson::dom::array attributes_array, Program *program) {
Since this returns nothing, the caller can't know if the function failed. Checking for `program == NULL` won't work because the pointer (but not the contents) is a copy, so whatever assignment you do inside won't be seen by the caller.

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +			strcpy(program->attributes.data[i], elem.get_c_str().value());
This is a `nullptr` dereference. Let's assume `elements == 1` and the first iteration fails to allocate. `program == NULL`. Because the loop doesn't `break` on error, line 38 attempts to access `program->attributes`, but `program` is `NULL`. This is UB and all bets are off.

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +		if (program->attributes.length > 0) {
This `if` is unnecessary. If `program->attributes.length == 0` we won't go inside the loop, and because `free(NULL)` is actually well defined, it's OK to `free(program->attributes.data)` even if it's `NULL`. Consider it just a nit though, since the code is still correct here.

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +	program->data = (felt_t *)malloc(elements * sizeof(felt_t));
While the result of `malloc` is __extremely__ unlikely to be `NULL` in modern operating systems (not necessarily in embedded), I find it odd that you check for it in other places but not here. Please consider either assuming it nullable everywhere or nowhere, but be consistent about it.

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +		from(felt, num);
Shouldn't this be `felt_from` or similar?

2023-07-20 17:37 UTC, Oppen commented on src/parser.cpp
> +	program->compiler_version = (char *)malloc(strlen(compiler_version) * sizeof(char *));
`strlen` doesn't include the null terminator, so we probably want to add one `char`. Also, if this is a string we should allocate elements of size `sizeof(char)`, not `sizeof(char*)`.

2023-07-20 17:37 UTC, Oppen commented on test/parser_test.c
> +	}
This is never `true`. `num_values` is always `2`.

2023-07-20 17:39 UTC, mmsc2 commented on lambdaworks/lib/lambdaworks.h
> +#pragma once
yeah, but we have being using include guards. maybe i is a good idea o standardize one.

2023-07-20 17:39 UTC, mmsc2 commented on lambdaworks/lib/lambdaworks.h
> +#pragma once
pragma once is supposed to be faster and well supported. we should take a decision and go fot it

2023-07-21 16:01 UTC, toni-calvin commented on src/parser.h
> +#endif
done

2023-07-21 16:01 UTC, toni-calvin commented on src/parser.cpp
> +	sscanf(hex, "%" SCNx64, &num);
done

2023-07-21 16:08 UTC, toni-calvin commented on src/parser.cpp
> +		from(felt, num);
I am using the already defined functions in lambdaworks.h, should i change it?

2023-07-21 16:13 UTC, toni-calvin commented on src/parser.cpp
> +		program = nullptr;
Should if it failed should i set the array length to 0 and the array to nullptr and return right away? 
Letting the checking when the array is used?

2023-07-21 16:15 UTC, toni-calvin commented on src/parser.cpp
> +void parse_attributes(simdjson::dom::array attributes_array, Program *program) {
So program should never be set to null?, only when the initial allocation is done, otherwise only the contents can be null if there's an error while parsing them?

2023-07-21 16:20 UTC, toni-calvin commented on src/parser.cpp
> +			strcpy(program->attributes.data[i], elem.get_c_str().value());
I understand, my proposed solution is to ouput which element index has caused the error. 
Adding also the else sequence on the strcpy. 
Should i create a boolean field declaring an array contains errors or should i set all the array to null?

2023-07-21 16:25 UTC, toni-calvin commented on src/parser.cpp
> +	program->data = (felt_t *)malloc(elements * sizeof(felt_t));
My proposed solution is to set the program->data to nullptr and return to main execution.

2023-07-21 16:26 UTC, toni-calvin commented on src/parser.cpp
> +	program->compiler_version = (char *)malloc(strlen(compiler_version) * sizeof(char *));
Right! Thanks for your correction, solved.

2023-07-21 16:30 UTC, toni-calvin commented on test/parser_test.c
> +	}
My fault! I'll watch to not happen again

2023-07-21 16:42 UTC, toni-calvin commented on lambdaworks/lib/lambdaworks.h
> +#pragma once
I've changed all parser header files to use #pragma once since it seems well supported and easier to use. Once the team make a decision i will change it if necessary.

2023-07-21 18:21 UTC, Oppen commented on src/parser.cpp
> +		from(felt, num);
I'm not sure the change is merged, but if it is then you should rebase.

2023-07-24 11:53 UTC, jrchatruc approved these changes

2023-07-25 10:06 UTC, merged