Add some basic data types
lambdaclass/cairo-vm.c pull request #2
Opened 2023-07-06 20:14 UTC by entropidelic

2023-07-07 15:47 UTC, jrchatruc commented
This looks good, but I believe the code should go under the `pkg` directory, right @Arkenan?

2023-07-07 15:55 UTC, entropidelic commented
> This looks good, but I believe the code should go under the `pkg` directory, right @Arkenan?

I think you are right, I'll fix that in a second

2023-07-07 16:31 UTC, Arkenan requested changes

2023-07-07 16:31 UTC, Arkenan commented on pkg/vm/memory/relocatable.go
> +}
This doesn't look like valid Go. There's no structural pattern matching here. Interfaces group types by their behavior: they define a series of methods that need to be implemented by a member type.

If we want Relocatable and Int (maybe we don't need to explicitely create the Int type) we need to think what is the behavior they share and describe it in methods.

2023-07-10 13:32 UTC, jrchatruc approved these changes

2023-07-10 15:42 UTC, merged