Add memory documentation
lambdaclass/cairo-vm.c pull request #28
Opened 2023-07-26 16:01 UTC by fmoletta

2023-07-26 16:29 UTC, toni-calvin commented on README.md
> +- `memory_insert`: Inserts a `maybe_relocatable` value at an address indicated by a `relocatable` pointer. For this operation to succed, the pointer's segment_index must be an existing segment (creat
mustn't

2023-07-26 16:29 UTC, toni-calvin commented on README.md
> +During execution, the memory consists of segments of varying lenght, and they can be accessed by indicating their segment index, and the offset within that segment. When the run is finished, a reloca
length

2023-07-26 18:04 UTC, fmoletta commented on README.md
> +- `memory_insert`: Inserts a `maybe_relocatable` value at an address indicated by a `relocatable` pointer. For this operation to succed, the pointer's segment_index must be an existing segment (creat
Nice catch!

2023-07-26 18:04 UTC, fmoletta commented on README.md
> +During execution, the memory consists of segments of varying lenght, and they can be accessed by indicating their segment index, and the offset within that segment. When the run is finished, a reloca
ty

2023-07-26 19:56 UTC, gabrielbosio requested changes
Looks good, though I found some typos

2023-07-26 19:56 UTC, gabrielbosio commented on README.md
> +The cairo memory is made up of contiguous segments of variable length identified by their index. The first segment (index 0) is the program segment, which stores the instructions of a cairo program.
```suggestion
The cairo memory is made up of contiguous segments of variable length identified by their index. The first segment (index 0) is the program segment, which stores the instructions of a cairo program. The following segment (index 1) is the execution segment, which holds the values that are created along the execution of the vm. The following group of segments are the builtin segments, one for each builtin used by the program, and which hold values used by the builtin runners. The last group of segments are the user segments, which represent data structures created by the user, for example, when creating an array on a cairo program, that array will be represented in memory as its own segment.
```

2023-07-26 19:56 UTC, gabrielbosio commented on README.md
> +- `memory_insert`: Inserts a `maybe_relocatable` value at an address indicated by a `relocatable` pointer. For this operation to succed, the pointer's segment_index must be an existing segment (creat
```suggestion
- `memory_insert`: Inserts a `maybe_relocatable` value at an address indicated by a `relocatable` pointer. For this operation to succeed, the pointer's segment_index must be an existing segment (created using `memory_add_segment`), and there mustn't be a value stored at that address, as the memory is immutable after its been written once. If there is a value already stored at that address but it is equal to the value to be inserted then the operation will be successful.
```

2023-07-26 20:05 UTC, fmoletta commented on README.md
> +The cairo memory is made up of contiguous segments of variable length identified by their index. The first segment (index 0) is the program segment, which stores the instructions of a cairo program.
TY

2023-07-26 20:13 UTC, gabrielbosio approved these changes

2023-07-26 20:18 UTC, gabrielbosio commented on README.md
> +    9 (base[2] + 0) -> 1
If the idea is to make the doc look like this, you can add another newline between  `0:0 -> 1`, `0:1 -> 4`, etc., because now it shows everything in the same line.
The md file would look like this:

```
For example, if we have this memory represented by address, value pairs:

0:0 -> 1

0:1 -> 4

0:2 -> 7

1:0 -> 8
...
```

2023-07-27 08:50 UTC, jrchatruc commented on README.md
> +The cairo memory is made up of contiguous segments of variable length identified by their index. The first segment (index 0) is the program segment, which stores the instructions of a cairo program.
> The following segment (index 1) is the execution segment, which holds the values that are created along the execution of the vm.

What does this mean exactly? Stack frames? Values that in other VMs are stored in general purpose registers but here we don't have those? Can we give some examples of the type of values created during execution that are stored in the execution segment?

2023-07-27 08:53 UTC, jrchatruc commented on README.md
> +1- The size of each segment is calculated (The size is equal to the highest offset within the segment + 1, and not the amount of `maybe_relocatable` values, as there can be gaps)
Can we give a brief explanation of memory gaps and why they occur before this?

2023-07-27 08:55 UTC, jrchatruc requested changes
Looks good! left two comments on things to expand on

2023-07-27 13:33 UTC, toni-calvin commented on README.md
> +    2 -> 0
```
    2 -> 0
```
Why is it 0? Highest offset of segment 2 is 0 + 1 should not be 1?

2023-07-27 13:43 UTC, fmoletta commented on README.md
> +    2 -> 0
Yes! nice catch!

2023-07-27 15:16 UTC, jrchatruc approved these changes

2023-07-27 15:53 UTC, toni-calvin approved these changes

2023-07-27 16:33 UTC, merged